### ISSUE TITLE
Can I use the mod item images to make a Lunchbox that can be used in Minecraft version 1.20.1

### ISSUE THREAD

**Issue by Mythos-404** [Nova-Committee/MinersLunchbox#4]
**refer the title or subject**

**Comment by moechakucha** [comment]
wdym, a standalone port or a pr?
if the former im not sure, if the latter go ahead

**Comment by Mythos-404** [comment]
Because itemnet is not compatible with Minecraft version 1.20.1 it needs to be refactored for the most part.
Pr is better, but it will take a while.

**Comment by Mythos-404** [comment]
I've also changed the project to be written in kotlin. Is that okay?

**Comment by moechakucha** [comment]
i'd prefer to use java, i dont see a good reason to use kotlin here

**Comment by Mythos-404** [comment]
Okay, I'll switch back to java.
I'm mostly practicing kotlin.
